app:
  name: "Plant Watcher"
  colors:
    background: "#5ace00"
    text: "#FEFEFE"

server:
  host: 0.0.0.0
  port: 5000
  debug: false

browser:
  url: http://${server.host}:${server.port}/
  open: true

serial:
  port: "/dev/ttyACM0"
  baudrate: 9600

lux_model:
  m: -1.549783691424802656e+00
  b: 6.755025013829503600e+00
  R: 5.15e+03
  Vin: 5.0
