app:
  name: "Plant Watcher"
  colors:
    background: "#00b34b"
    text: "#FEFFFF"

server:
  host: 0.0.0.0
  port: 5000
  debug: false

browser:
  url: http://${server.host}:${server.port}/
  open: true

serial:
  port: "/dev/ttyACM0"
  baudrate: 9600

lux_model:
  m: -1.450249716657489252e+00
  b: 6.476968488065346641e+00
  R: 5.15e+03
  Vin: 5.0
