defaults:
  - lux_model: all_circuits

app:
  name: "Plant Watcher"
  colors:
    background: "#00b34b"
    text: "#FEFFFF"

server:
  host: 0.0.0.0
  port: 5000
  debug: true

browser:
  url: http://${server.host}:${server.port}/
  open: false

serial:
  port: "/dev/ttyACM0"
  baudrate: 9600
